### PR TITLE
Local vs root paths

### PR DESCRIPTION
**Pull request by ashleyharvey**
Addresses issue #210

### CODE REVIEW

**Comment by oniony** [comment]
Not sure why this is replacing `cp` with `gcp` (which doesn't even exist on my machine)?

**Comment by ashleyharvey** [comment]
Because macOS ships with BSD cp, which behaves differently from GNU cp. 
If you have homebrew, simply `brew install gcp`.

**Comment by oniony** [comment]
I don't have homebrew. I don't want TMSU to be dependent upon non-standard stuff. It would be better if we change the `Makefile` to use BSD `cp`.

**Comment by oniony** [comment]
I think 1. back out the `gcp` changes, as they're not related to what this ticket is addressing. Fixing the `Makefile` for Mac can be a separate ticket. Would be good to know exactly which options it's failing with, is it the `-t`?

**Comment by ashleyharvey** [comment]
> I think 1. back out the `gcp` changes, as they're not related to what this ticket is addressing. Fixing the `Makefile` for Mac can be a separate ticket.

Understood.

> Would be good to know exactly which options it's failing with, is it the `-t`?

Yep!

**Comment by ashleyharvey** [comment]
> I don't have homebrew. I don't want TMSU to be dependent upon non-standard stuff. It would be better if we change the `Makefile` to use BSD `cp`.

Agreed, okay.

**Pull request closed without merging**
