### PR TITLE
Fix SQL query typo

### PR DESCRIPTION
**Pull request by ashleyharvey**
Addresses issue #209

### CODE REVIEW

**Comment by jsmaniac** [comment]
Hi @ashleyharvey , it seems like you pushed some useful but unrelated commits to this PR's branch. Since these commits are already included in #218 and #184 (and partially in #214), you can do so as follows:

```
# Getting a clean slate in GIT is a nightmare, for a simple one-off change a fresh clone is easier
git clone https://github.com/oniony/TMSU /tmp/TMSU-fix-sql-query-typo

# Temporarily switch to this directory
pushd /tmp/TMSU-fix-sql-query-typo

# download the fix-sql-query-typo version from your github and the previous versions too
git fetch https://github.com/ashleyharvey/TMSU fix-sql-query-typo

# Compute the diff between the "Address SQL typo as per issue #209" version and the version before it,
# and apply that diff on top of the current version (which is the same version as the latest official version)
git cherry-pick 958c40e

# Overwrite the "fix-sql-query-typo" with the hash of HEAD (current commit) on the github server
git push git@github.com/ashleyharvey/TMSU HEAD:fix-sql-query-typo

# go back to where you were and enjoy your day
popd
```

**Comment by ashleyharvey** [comment]
> Hi @ashleyharvey , it seems like you pushed some useful but unrelated commits to this PR's branch. Since these commits are already included in #218 and #184 (and partially in #214), you can do so as follows:
> 
> ```
> # Getting a clean slate in GIT is a nightmare, for a simple one-off change a fresh clone is easier
> git clone https://github.com/oniony/TMSU /tmp/TMSU-fix-sql-query-typo
> 
> # Temporarily switch to this directory
> pushd /tmp/TMSU-fix-sql-query-typo
> 
> # download the fix-sql-query-typo version from your github and the previous versions too
> git fetch https://github.com/ashleyharvey/TMSU fix-sql-query-typo
> 
> # Compute the diff between the "Address SQL typo as per issue #209" version and the version before it,
> # and apply that diff on top of the current version (which is the same version as the latest official version)
> git cherry-pick 958c40e
> 
> # Overwrite the "fix-sql-query-typo" with the hash of HEAD (current commit) on the github server
> git push git@github.com/ashleyharvey/TMSU HEAD:fix-sql-query-typo
> 
> # go back to where you were and enjoy your day :-)
> popd
> ```

Thank you for the help in cleaning this up. I've done a bunch of work with git since I pushed these changes so (hopefully) I'm less messy with it now. I tried to follow your instructions and ended up replacing `/` with `:` in your git push line, but here's what I got back from git:

```
To github.com:ashleyharvey/TMSU
 ! [rejected]        HEAD -> fix-sql-query-typo (non-fast-forward)
error: failed to push some refs to 'github.com:ashleyharvey/TMSU'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by jsmaniac** [comment]
@ashleyharvey Oops, my bad, that should've been

```
git push --force git@github.com:ashleyharvey/TMSU HEAD:fix-sql-query-typo
```

By default GIT refuses to overwrite a pointer with a commit that isn't a successor of the pointer's current target, in order to avoid accidentally loosing parts of the history. Since the goal was to *remove* some commits from the history (instead of adding some further changes or merging with other existing changes), we need to `--force` it.

**Comment by ashleyharvey** [comment]
> @ashleyharvey Oops, my bad, that should've been
> 
> ```
> git push --force git@github.com:ashleyharvey/TMSU HEAD:fix-sql-query-typo
> ```
> 
> By default GIT refuses to overwrite a pointer with a commit that isn't a successor of the pointer's current target, in order to avoid accidentally loosing parts of the history. Since the goal was to _remove_ some commits from the history (instead of adding some further changes or merging with other existing changes), we need to `--force` it.

Okay, done!

**Pull request merged**
